"""
Django settings for suits_me project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from dotenv import load_dotenv
load_dotenv()

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

ENVIRONMENT = os.getenv('ENVIRONMENT', default='production')
ENVIRONMENT='production'
# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
else:
    DEBUG = False


DEFAULT_ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'localhost:8000',
      'suits-me.herokuapp.com',
    'suits_me.onrender.com',
    '64af3df035ed.ngrok-free.app',
    'www.suitsme.com',
    'suitsme.up.railway.app',
]
HEROKU_APP_NAME = os.getenv('HEROKU_APP_NAME')
if HEROKU_APP_NAME:
    DEFAULT_ALLOWED_HOSTS.append(f"{HEROKU_APP_NAME}.herokuapp.com")

EXTRA_ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]
ALLOWED_HOSTS = DEFAULT_ALLOWED_HOSTS + EXTRA_ALLOWED_HOSTS
INTERNAL_IPS = ('127.0.0.1','localhost:8000', '2811935e10f8.ngrok-free.app',)

CSRF_TRUSTED_ORIGINS = [
    'https://64af3df035ed.ngrok-free.app',
    'https://suitsme.up.railway.app',
]
if HEROKU_APP_NAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{HEROKU_APP_NAME}.herokuapp.com")
CSRF_TRUSTED_ORIGINS += [
    origin.strip()
    for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'django_cleanup.apps.CleanupConfig',
    'django_htmx',
    'django.contrib.sites',
    'django_ckeditor_5',
    'anymail',
    'a_main',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'suits_me.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suits_me.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUD_API_KEY'),
    'API_SECRET': os.getenv('CLOUD_API_SECRET'),
}


STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
CKEDITOR_5_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
CKEDITOR_5_UPLOAD_PATH = "ckeditor/uploads/"



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Anymail configuration
EMAIL_BACKEND = 'anymail.backends.brevo.EmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@suits_me.com')

# Brevo settings
ANYMAIL = {
    'BREVO_API_KEY': os.getenv('BREVO_API_KEY'),
}

CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'en',
      
        'toolbar': [
            'heading', '|',
            'fontSize', 'fontFamily', '|',  
            'bold', 'italic', 'underline', 'strikethrough', 'highlight', '|',
            'link','alignment', '|', 
            'bulletedList', 'numberedList', '|',
            'blockQuote', 'code', 'codeBlock', '|',
            'link', 'imageUpload', 'mediaEmbed', 'horizontalLine', 'specialChasuits_meters', '|', 
            'insertTable', 'tableColumn', 'tableRow', 'mergeTableCells', '|',
            'undo','redo', '|',
            'findAndReplace', 'selectAll', '|',
            'sourceEditing',
        ],
        'mediaEmbed': {
            'previewsInData': True,
             'toolbar': [
                'mediaEmbed',
                'toggleMediaEmbed',
                'mediaEmbedSize'  # Adds size control option
            ],
            # Define default dimensions
            'defaultSize': {
                'width': '640',
                'height': '360'
            },
            # You can also specify responsive dimensions
            'responsive': True,
        },
    
        'extraAllowedContent': 'iframe[*]; div[*]', 
         # Configure headings
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'},
            ]
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignCenter', 'imageStyle:full','imageStyle:side', 'imageStyle:alignRight', '|',
                'resizeImage'
            ]
        },
        'simpleUpload': {
               'uploadUrl': '/ckeditor5/image_upload/',
           },
        'height': 300,
        'width': '100%',
        'extraAllowedContent': True,
        
         # Font options
        'fontSize': {
            'options': [
                9, 11, 13, 'default', 17, 19, 21
            ]
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Sans Unicode, Lucida Grande, sans-serif',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, Helvetica, sans-serif',
                'Verdana, Geneva, sans-serif'
            ]
        },
    },
}

CKEDITOR_5_ALLOW_ALL_FILE_TYPES = True
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "authenticated"